### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by girls-incode** [khan4019/BangularBank#1]
**>ng serve** 

**results with error:**

_Your global Angular CLI version (1.1.3) is greater than your local
version (1.0.0-rc.2). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is running on http://localhost:4200 **
 86% hashingcrypto.js:97
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:97:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\dependencies\HarmonyExportImportedSpecifierDependency.js:144:
8)
    at E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\Module.js:162:41)
    at NormalModule.updateHash (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\NormalModule.js:327:30)
    at modules.forEach.m (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\Chunk.js:253:16)
    at Compilation.createHash (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\Compilation.js:1121:10)
    at sealPart2 (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\Compilation.js:605:9)
    at next (E:\workspace\angularcli\BangularBank-master\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (E:\workspace\angularcli\BangularBank-master\node_modules\webpack\lib\ProgressPlugin.js:110:5)
    at next (E:\workspace\angularcli\BangularBank-master\node_modules\tapable\lib\Tapable.js:140:14)
    at ExtractTextPlugin.<anonymous> (E:\workspace\angularcli\BangularBank-master\node_modules\extract-text-webpack-plugin\index.js:305:5)_

**Comment by fodorelli** [comment]
make sure u don't use just "npm install" ...
the corect way is "npm install -g "at"angular/cli "
